### PR TITLE
fix(emoji picker): fix copy button

### LINKED ISSUE #555: [BUG] Emoji-picker
**Which tool is impacted?**
Emoji-picker

**To Reproduce**
When clicking an emoji to text it should copy it to clipboard (it shows a message for it) but it doesn't seem to work in Windows 10 Edge/Firefox/Chrome. When pasting it somewhere it paste the thing I had on clipboard. Manual ctrl+c / ctrl+v for copying works

**Expected behavior**
It copies the emoji/text to my clipboard.

**Screenshots**

**Configuration (please complete the following information):**

- Device: Desktop computer
- OS: Windows 10
- Browser Edge/Chrome/Firefox
- Version all latest (browsers)

**Additional context**
Thanks for adding the requested feature, really like it!... You even made it better to automatically copy it to the clipboard, but it doesn't work (for me)

### PR DESCRIPTION
**Pull request by CorentinTh**
closes #555

### CODE REVIEW

File: src/composable/copy.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ export function useCopy({ source, text = 'Copied to the clipboard' }: { source?:
 
   return {
     async copy(content?: string, { notificationMessage }: { notificationMessage?: string } = {}) {
-      await copy();
+      await copy(content);
```
Comment (Mert75) [inline src/composable/copy.ts:10]: This causes breaking functionality, for instance you can verify on UUIDs: you will receive [object PointerEvent]
