### PR TITLE
fix(roman-numeral-converter):  checks for valid input and conversion …

### LINKED ISSUE #274: [BUG]  Incorrect Roman number conversion - Roman to Arabic
**Describe the bug**
Roman number converter - Conversion from roman to arabic incorrect

**To Reproduce**
1. Go to 'Roman numeral converter'
2. Add 'IVX' to 'Roman to Arabic'
3. You will see '4'. IVX is not valid roman numerical
4. Can be done with other values such as 'IXX' which is also invalid

**Expected behavior**
Correct conversion

**Screenshots**
image

### PR DESCRIPTION
**Pull request by cgoIT**
…enhancements

Validates if numeral values are between 1 and 3999999. Validates if a roman number is valid.

Fixes #274

### CODE REVIEW

**Comment by cgoIT** [comment]
On thing I just recognized is, that the copy button doesn't make to much sense if the numeral value is greater than 3999. Maybe it would be an option to disable the copy button if the number is greater than 3999?

File: src/tools/roman-numeral-converter/roman-numeral-converter.vue [hunk 1]
```diff
@@ -2,21 +2,27 @@
   <div>
     <n-card title="Arabic to roman">
       <n-space align="center" justify="space-between">
-        <n-input-number v-model:value="inputNumeral" :min="1" style="width: 200px" :show-button="false" />
+        <n-form-item v-bind="validationNumeral">
+          <n-input-number v-model:value="inputNumeral" :min="1" style="width: 200px" :show-button="false" />
+        </n-form-item>
         <div class="result">
-          {{ outputRoman }}
+          <span v-html="outputRoman"></span>
```
Comment (CorentinTh) [inline src/tools/roman-numeral-converter/roman-numeral-converter.vue:9]: I'm not a fan of v-html, it can lead to a huge security flaw, and is often synonyme of bad design

File: src/tools/roman-numeral-converter/roman-numeral-converter.vue [hunk 2]
```diff
@@ -25,16 +31,47 @@
...
+    },
+  ],
+});
+
 const { copy: copyRoman } = useCopy({ source: outputRoman, text: 'Roman number copied to the clipboard' });
 const { copy: copyArabic } = useCopy({ source: outputNumeral, text: 'Arabic number copied to the clipboard' });
+
+function isCopyRomanDisabled() {
+  return validationNumeral.validationStatus === 'error' || inputNumeral.value > 3999;
+}
```
Comment (CorentinTh) [inline src/tools/roman-numeral-converter/roman-numeral-converter.vue:74]: use a computed instead

**Review by CorentinTh — CHANGES_REQUESTED** [review]
Thank you for this PR, and sorry for taking so long to review it 

I think we can stick to roman number below 3999
I'm not trully fan of the span with overline, it's not inputable and nor copyable and force to use v-html which I dont really want in the app

**Review by CorentinTh — APPROVED** [review]
Looks great, thanks 🙏🏻
